name: KNN Model 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Set up checkout  
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install -r C:/Users/m.naja/P7/.github/workflows/requirements.txt 
    - name: Run tests
      run: |
        python test_script.py
